---
- name: ensure python-software-properties is installed
  apt: pkg=python-software-properties state=installed

- name: add rabbitmq official apt repository
  apt_repository: repo='deb http://www.rabbitmq.com/debian/ testing main' state=present

- name: install rabbitmq
#  apt: pkg=rabbitmq-server={{rabbitmq.version}} state=installed force=yes
  apt: pkg=rabbitmq-server state=installed force=yes

- name: enable rabbitmq plugins
  rabbitmq_plugin: names=rabbitmq_management,rabbitmq_tracing,rabbitmq_federation state=enabled
#  notify:
#  - restart rabbitmq

- name: add users
  rabbitmq_user: user={{rabbitmq.user}} password={{rabbitmq.password}} tags=administrator,{{rabbitmq.user}} vhost=/ configure_priv=.* write_priv=.* read_priv=.* state=present

- name: remove default guest user
  rabbitmq_user: user=guest state=absent

- name: restart rabbitmq
  service: name=rabbitmq-server state=restarted