---
# Retrieve the current hostname, because {{ ansible_hostname }} still contains the old name
- shell: hostname
  register: current_hostname

- name: Postgres | Install PG Packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
      - postgresql
      - postgresql-contrib
      - libpq-dev
      - python-psycopg2

- name: Change PG root pass
  become: yes
  become_user: postgres
  command: psql -c "ALTER USER postgres PASSWORD '{{ postgres.root_password }}';"

- name: ensure database is created
  become: yes
  become_user: postgres
  postgresql_db: name={{ postgres.database }}

- name: Create new database user
  become: yes
  become_user: postgres
  postgresql_user: db={{ postgres.database }} name={{ postgres.user }} password={{ postgres.password }} priv=ALL
