zend_extension=xdebug.so
xdebug.remote_enable = {{ xdebug.remouteEnable }}
xdebug.remote_host = {{ xdebug.remoteHost }}
xdebug.remote_port = {{ xdebug.remotePort }}
xdebug.idekey = {{ xdebug.ideKey }}
xdebug.remote_connect_back=1
xdebug.default_enable=1
xdebug.remote_autostart=1
xdebug.remote_handler=dbgp
xdebug.extended_info = 1
